In [1]:
import os
import llm4series as ls

token = os.getenv("OPENAI_API_KEY")

In [2]:
model = ls.LLM(model="gpt-5", api_key=token)

In [3]:
ts = ls.read_file("data/ETTh2.csv")
train, test = ts.split(start="2016-07-12 06:00:00", end="2016-09-20 05:00:00", periods=24)

In [5]:
prompt = ls.prompt(type="few_shot", ts=train, tsformat="csv", tstype="numeric", examples=3, forecast_horizon=24)

In [15]:
response = model.predict(prompt)

[INFO] HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

In [17]:
response.prediction

,HUFL,HULL,MUFL,MULL,LUFL,LULL,OT
date,,,,,,,
2016-09-20 06:00:00+00:00,41.298,11.979,36.804,8.873,3.646,1.215,28.213
2016-09-20 07:00:00+00:00,41.465,12.649,37.180,9.382,3.646,1.258,28.213
2016-09-20 08:00:00+00:00,36.020,8.377,32.060,5.763,3.646,1.684,29.312
2016-09-20 09:00:00+00:00,40.292,12.146,37.742,9.757,2.356,0.000,30.850
2016-09-20 10:00:00+00:00,35.853,8.377,33.936,6.487,2.356,0.000,33.925
2016-09-20 11:00:00+00:00,38.031,10.722,35.464,8.256,2.356,0.000,37.222
2016-09-20 12:00:00+00:00,41.884,12.900,39.565,10.159,2.356,0.000,38.979
2016-09-20 13:00:00+00:00,40.627,13.403,38.252,10.642,2.356,0.000,39.419
2016-09-20 14:00:00+00:00,38.952,13.068,36.295,10.159,2.356,1.226,40.518
2016-09-20 15:00:00+00:00,41.716,14.073,39.217,11.205,2.356,1.226,41.396
2016-09-20 16:00:00+00:00,44.146,14.827,40.584,11.419,3.582,1.237,40.518
2016-09-20 17:00:00+00:00,46.575,15.665,40.530,11.098,6.098,2.527,38.320
2016-09-20 18:00:00+00:00,44.900,13.989,39.083,9.811,5.970,2.527,36.123
2016-09-20 19:00:00+00:00,39.622,10.387,34.713,7.130,4.798,2.527,34.585
2016-09-20 20:00:00+00:00,40.963,11.895,35.947,8.149,4.958,2.527,33.486
2016-09-20 21:00:00+00:00,45.318,14.157,39.083,9.784,6.248,2.527,32.607
2016-09-20 22:00:00+00:00,40.963,12.900,35.732,9.302,4.787,2.527,31.729
2016-09-20 23:00:00+00:00,36.858,10.890,32.355,7.747,4.798,2.527,30.850
2016-09-21 00:00:00+00:00,36.858,12.063,30.961,7.452,4.830,1.311,29.751
2016-09-21 01:00:00+00:00,38.114,11.895,33.266,8.712,4.830,1.247,28.652
2016-09-21 02:00:00+00:00,35.685,10.974,33.212,8.605,3.358,1.290,27.773
2016-09-21 03:00:00+00:00,39.203,11.979,33.802,8.578,4.606,1.343,27.334
2016-09-21 04:00:00+00:00,38.449,12.230,33.748,8.926,4.286,1.343,26.236
2016-09-21 05:00:00+00:00,39.622,12.481,35.169,9.570,4.286,1.343,25.796

In [16]:
print(response.time)
print(response.input_tokens)
print(response.output_tokens)

62.52412033081055
75904
5205

In [18]:
ls.plot(test, response.prediction, kind='line', groups=["Real", "Predicted"], title="Forecast vs Actual", xlabel="Time", ylabel="Value")

In [19]:
ls.metrics(response.prediction["OT"], test["OT"])

         OT
smape  3.47
mae    1.07
rmse   1.32